Каркас приложения
Natal1a-Chuklina/java-filmorate pull request #1
Opened 2023-02-02 15:04 UTC by Natal1a-Chuklina

2023-02-02 20:12 UTC, z8q requested changes
Привет, Наталья!

Оставил комментарии :)

2023-02-02 20:12 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Logger logger = LoggerFactory.getLogger(FilmController.class);
Можно вместо этой строки попробовать поставить над классом `@Slf4j`
Вызов логгера будет такого вида:
log.info("Some info");

2023-02-02 20:12 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            logger.info("Выполнена попытка добавить фильме с уже существующим id = {}.", film.getId());
При ошибках стоит использовать log.error

2023-02-02 20:12 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        BeanUtils.copyProperties(film, films.get(film.getId()), "id");
Чем такой способ лучше `map.replace(key, value);`?

2023-02-02 20:12 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @PostMapping
Будет правильно добавлять значения к аннотациям контроллеров, например:
@PostMapping("/create")
Если будет два POST метода, все равно это придется сделать

2023-02-02 20:12 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @EqualsAndHashCode.Include
Мне не очень нравится такая идея.
Если где-то в новых сервисных классах будем создавать объекты Film:
Film x = new Film(name1, description1, LocalDate.of(2023, 2, 1), 1);
Film y = new Film(name2, description2, LocalDate.of(2023, 2, 2), 2);
что даст x.equals(y)?
Можно посоветоваться с наставником

2023-02-02 20:12 UTC, z8q commented on src/test/java/ru/yandex/practicum/filmorate/model/validate/StartDateValidatorTest.java
> +class StartDateValidatorTest {
Можно было бы вызовы контроллеров тоже потестировать

2023-02-02 20:12 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @StartDateValidation(date = "28.12.1895", message = "Дата релиза должна быть позже 28 декабря 1895 года.")
Тут интересно придумано :)

2023-02-02 20:12 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +        this.name = (name == null || name.isBlank()) ? login : name;
В конструкторе проверку имени не сразу заметил.
Возможно было бы лучше выводить проверку и setName if blank в какой-то метод

2023-02-03 15:27 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Logger logger = LoggerFactory.getLogger(FilmController.class);
Сделала.

2023-02-03 15:31 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            logger.info("Выполнена попытка добавить фильме с уже существующим id = {}.", film.getId());
Уровень error приберегла для более тяжелых ситуаций. :) Переделала на уровень warn.

2023-02-03 15:33 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        BeanUtils.copyProperties(film, films.get(film.getId()), "id");
Только тем, что можно задать поля, которые при копировании будут игнорироваться и останутся прежними.

2023-02-03 15:56 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @PostMapping
Я бы с радостью сама что-то поменяла, но в ТЗ нам дали тесты в postman (https://github.com/yandex-praktikum/java-filmorate/blob/controllers-films-users/postman/sprint.json), по которым можно судить о корректности работы приложения, как я понимаю, они так же запускаются при пул реквесте. Поэтому возможности что-то сильно менять и как-то экспериментировать у меня нет.

2023-02-03 15:57 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @EqualsAndHashCode.Include
Переделала.

2023-02-03 15:57 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +        this.name = (name == null || name.isBlank()) ? login : name;
Переделала

2023-02-03 16:11 UTC, Natal1a-Chuklina commented on src/test/java/ru/yandex/practicum/filmorate/model/validate/StartDateValidatorTest.java
> +class StartDateValidatorTest {
Предполагаю, что в следующих модулях нам подробно расскажут про тестирование и я протестирую контроллеры. Пока просили протестировать только валидацию.

2023-02-04 15:56 UTC, z8q approved these changes

2023-02-04 15:56 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +Я не стала делать абстрактный контроллер и наследовать от него два других, мне показалось, что это не сильно хорошая идея.
Согласен. Не уверен, что это может пригодится. 
Общую логику можно потом будет реализовать в сервисных классах.
Если только через абстрактный класс определять, какие методы должны обязательно реализовывать контроллеры. Но не знаю, есть ли смысл...)

2023-02-04 15:56 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @PostMapping
Хорошо,
Но если возьмем этот пример, что мы используем `@RequestMapping("/users")`, а на самих методах только аннотации без определения.
Создадим два post метода, 
При post-вызове /users будет ошибка

2023-02-14 23:05 UTC, merged