feat: добавить получения рекоммендаций для пользователя
Natal1a-Chuklina/java-filmorate pull request #11
Opened 2023-04-02 13:09 UTC by kriulkin

ПР рекомендаций с develop

2023-04-03 02:12 UTC, AndreyMeltsov requested changes

2023-04-03 02:12 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/controller/RecommendationController.java
> +public class RecommendationController {
На мой взгляд делать для этой фишки отдельный контроллер излишне. Можно было добавить этот эндпоинт в UserController

2023-04-03 02:12 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationService.java
> +public class RecommendationService {
То же самое, на мой взгляд этот один метод можно было добавить в UserSerice

2023-04-03 02:12 UTC, AndreyMeltsov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    @Test
Тесты это круто!

2023-04-03 02:19 UTC, kriulkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/RecommendationController.java
> +public class RecommendationController {
Это действительно спорный момент! при первой итерации реализации этот функционал я добавил контроллер UserController, с сервисом тоже самое. Но во время qa вебинара. Егор озвучил точку зрения, по логике которой  добавлять в существующий сервис бин filmStorage только из-за одного метода это оверхед, он предложил добавить отдельный сервис, и соответственно, отдельный контроллер.

2023-04-03 02:19 UTC, kriulkin commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationService.java
> +public class RecommendationService {
смотри предыдущий пункт

2023-04-03 02:19 UTC, kriulkin commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    @Test
во истину :)

2023-04-03 02:23 UTC, AndreyMeltsov approved these changes

2023-04-03 05:39 UTC, Natal1a-Chuklina commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +    @Test
Присоединяюсь😃

2023-04-03 08:31 UTC, alexexus commented on src/main/java/ru/yandex/practicum/filmorate/controller/RecommendationController.java
> +public class RecommendationController {
Мне кажется правильным делать отдельные классы, потому что в будущем у рекомендаций могут появится новые методы и новые эндпоинты и тогда юсер контроллер будет попросту захламлен этими методами

2023-04-03 09:00 UTC, alexexus commented on src/main/java/ru/yandex/practicum/filmorate/controller/RecommendationController.java
> +}
Нету пустой строчки в конце кода

2023-04-03 09:00 UTC, alexexus commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationService.java
> +}
Нету пустой строчки в конце кода

2023-04-03 09:00 UTC, alexexus commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +}
Нету пустой строчки в конце кода

2023-04-03 11:45 UTC, kriulkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/RecommendationController.java
> +}
Да, действительно! почему то они отсутствуют только в "моих" файлах. Добавлю. Можешь объяснить зачем они нужны?

2023-04-03 11:56 UTC, alexexus commented on src/main/java/ru/yandex/practicum/filmorate/controller/RecommendationController.java
> +}
https://semakin.dev/2020/05/no_newline_at_end_of_file/

2023-04-05 01:55 UTC, Natal1a-Chuklina requested changes

2023-04-05 01:55 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                        "WHERE f.id in ( " +
Можно упростить подзапрос до:
SELECT l2.film_id
FROM likes as l2
WHERE l2.user_id = ?

2023-04-05 01:55 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +                        "    SELECT user_id FROM ( " +
Немного не поняла, в чем задача этого подзапроса. Насколько я поняла задание, нужно получить список всех пользователей, которые оставили лайк хотя бы одному фильму из тех, что лайкнул пользователь, которому мы составляем рекомендации. Для этого достаточно подзапроса:
WHERE u.id IN (SELECT user_id
FROM likes
WHERE user_id <> 2
  AND film_id in
    (SELECT film_id
     FROM likes
     WHERE user_id = 2)
GROUP BY user_id
ORDER BY COUNT (user_id) DESC)
сортировка в данном случае избыточна, так как по заданию нужно получить список всех пользователей со схожими интересами, но в будущем может понадобиться ограничить этот список каким-то числом и, следовательно, сделать так, чтобы в него попали самые точные соответствия, поэтому я ее добавила.

2023-04-05 01:55 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +    public Collection<User> getSimilarInterestUsers(int userId) {
Достаточно, чтобы метод возвращал не коллекцию пользователей, а коллекцию id пользователей, так как в дальнейшем из всей информации о пользователе со схожими интересами ты используешь только его id.

2023-04-06 15:05 UTC, Natal1a-Chuklina approved these changes

2023-04-07 14:36 UTC, merged