ветка Add-feed
Natal1a-Chuklina/java-filmorate pull request #12
Opened 2023-04-03 18:10 UTC by AleksandrGimanov

2023-04-05 01:38 UTC, AndreyMeltsov requested changes

2023-04-05 01:38 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/mapper/HistoryEventUserMapper.java
> +public class HistoryEventUserMapper implements RowMapper<EventUser> {
Немного путает название маппера "HistoryEventUserMapper". Почему не просто "EventUserMapper?

2023-04-05 01:38 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final HistoryService history;
historyService понятнее. а еще лучше eventService

2023-04-05 01:38 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/model/EventUser.java
> +public class EventUser {
Вообще мне кажется с названиями классов какая-то сумятица: На мой взгляд класс в модели с событием можно назвать просто Event. Маппер - EventMapper, сервис - EventService, сторадж EventStorage.

2023-04-05 01:38 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/service/HistoryService.java
> +    private final HistoryEventDbUserStorage history;
eventStorage

2023-04-05 01:38 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/service/HistoryService.java
> +    public List<EventUser> getHistoryUser(int userId) {
getEvents

2023-04-05 01:38 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/service/HistoryService.java
> +    public void createHistoryUser(int userId, OperationStatus operation, EventTypeStatus eventType, int entityId) {
createEvent

2023-04-05 01:38 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/service/HistoryService.java
> +
лишняя строчка))

2023-04-05 01:38 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/storage/HistoryEventDbUserStorage.java
> +    public List<EventUser> findHistoryUserById(int userId) {
findEventsByUserId

2023-04-05 01:38 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/storage/HistoryEventDbUserStorage.java
> +    public void save(EventUser historyEventUser) {
addEvent

2023-04-05 01:38 UTC, AndreyMeltsov commented on src/main/resources/schema.sql
> +create TABLE IF NOT EXISTS history_user (
Я б таблицу назвал events

2023-04-05 06:23 UTC, AleksandrGimanov commented on src/main/java/ru/yandex/practicum/filmorate/mapper/HistoryEventUserMapper.java
> +public class HistoryEventUserMapper implements RowMapper<EventUser> {
я исходил из того что event это просто событие, а HistoryEvent уже история событий

2023-04-05 09:15 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/mapper/HistoryEventUserMapper.java
> +public class HistoryEventUserMapper implements RowMapper<EventUser> {
Но мапишь то ты именно событие.

2023-04-05 10:07 UTC, AndreyMeltsov approved these changes

2023-04-06 01:12 UTC, Natal1a-Chuklina requested changes

2023-04-06 01:12 UTC, Natal1a-Chuklina commented on src/main/resources/schema.sql
> +event_Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
Везде id с маленькой буквы, а тут с большой, возможно, это опечатка?

2023-04-06 01:12 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/EventService.java
> +        log.info("История действий пользователя с id = {} сохранена.", userId);
В этой логике, eventUser сохраняется только в том случае, если он не null, а сообщение, что история сохранена будет выведено в любом случае. Хотя, насколько я могу судить, eventUser никогда не будет null.

2023-04-06 01:12 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            eventService.createEvent(userId, OperationStatus.ADD, EventTypeStatus.LIKE, filmId);
Лучше выполнить добавление лайка, а потом добавить это событие в историю (поменять местами 87 и 88 строчки), так как метод addLike может при доработке измениться и, если что-то будет не учтено, может начать выбрасывать ошибку, при этом сам лайк не будет добавляться, а вот в историю это событие запишется.

2023-04-06 01:12 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            eventService.createEvent(userId, OperationStatus.REMOVE, EventTypeStatus.LIKE, filmId);
Ситуация аналогична прошлой.

2023-04-06 01:12 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        eventService.createEvent(review.getUserId(), OperationStatus.ADD, EventTypeStatus.REVIEW, review.getReviewId());
Можно заменить review.getUserId() на локальную переменную userId, которая уже существует.

2023-04-06 01:12 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        eventService.createEvent(review.getUserId(), OperationStatus.REMOVE, EventTypeStatus.REVIEW, review.getReviewId());
Лучше перенести добавление события в историю после выполнения этого события. Хорошим местом будет блок if.

2023-04-06 01:12 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            eventService.createEvent(userId, OperationStatus.REMOVE, EventTypeStatus.FRIEND, friendId);
Аналогично прошлым случаям.

2023-04-06 01:12 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/storage/EventDbStorage.java
> +        log.info("Данные о действии занесены в историю");
Можно в модель Event добавить аннотацию @ToString, а тут в info логи вывести еще и само событие с актуальным id (для этого нужно, чтобы бд вернула id созданной записи).

2023-04-06 08:53 UTC, Natal1a-Chuklina requested changes

2023-04-06 08:53 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/EventService.java
> +            eventDbStorage.add(eventUser);
Лишние отступы от левого края.

2023-04-06 09:06 UTC, Natal1a-Chuklina approved these changes

2023-04-06 09:06 UTC, merged