Расширение функционала приложения
Natal1a-Chuklina/java-filmorate pull request #15
Opened 2023-04-07 14:37 UTC by Natal1a-Chuklina

2023-04-08 14:38 UTC, z8q requested changes
Привет!

Комментарии оставил.
Есть не критичные, но кое-что стоит поправить

2023-04-08 14:38 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        return directorStorage.getDirectorById(id);
Тут можно было бы упростить.
На одну операцию – получение режиссёра, мы делаем два запроса.
Ошибку можно бросить, если при запросе к базе `getDirectorById`  director == null

2023-04-08 14:38 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  import lombok.extern.slf4j.Slf4j;
Создаю режиссера. 
{
"id": 1,
"name": "New director"
}
В таблице он появляется.

Потом создаю фильм, сразу с режиссером:
{
	"name": "New film",
	"releaseDate": "1999-04-30",
	"description": "New film about friends",
	"duration": 120,
	"mpa": { "id": 3},
	"genres": [{ "id": 1}],
	"director": [{ "id": 1}]
}

По какой-то причине не заполняется таблица FILM_DIRECTOR и в ответе видим такой JSON:
{
	"id": 2,
	"name": "New film",
	"description": "New film about friends",
	"releaseDate": "1999-04-30",
	"duration": 120,
	"mpa": {
		"id": 3,
		"name": "PG-13"
	},
	"genres": [
		{
			"id": 1,
			"name": "Комедия"
		}
	],
	"likes": [],
	"directors": []
}

2023-04-08 14:38 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getSortedFilmByQuery(@RequestParam(value = "query", required = false) String query,
Тут все ок. После правда по режиссеру не вывести пока, потому что не сохраняются.
На UPDATE в filmController тоже не удается добавить режиссера

2023-04-08 14:38 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/RecommendationController.java
> +    public Collection<Film> getRecommendations(@PathVariable int userId) {
Работает!

2023-04-08 14:38 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>  import lombok.extern.slf4j.Slf4j;
Создаем user 1-2-3
Добавляем в друзья
PUT http://localhost:8080/users/1/friends/3
потом
PUT http://localhost:8080/users/3/friends/1
Почему-то один из пользователей все равно остается в статусе UNCONFIRMED
И в базе происходит что-то странное:

`ID | FRIEND_1_ID | FRIEND_2_ID | STATUS_ID`
`1   	1	3	2`
`2	3	1	1`
`3	3	1	2`
`4	1	3	1`

2023-04-08 14:38 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +public class ReviewController {
Тут все хорошо

2023-04-08 14:38 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    @PutMapping("/{id}/dislike/{userId}")
Если один пользователь поставит лайк на ревью и потом дизлайк на это же ревью, все корректно считается

2023-04-08 14:38 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Collection<Event> getHistoryByUserId(@PathVariable int id) {
События записываются

2023-04-08 14:38 UTC, z8q commented on pom.xml
>  		<dependency>
Стоит в readme перечислить, какие задания были выполнены

2023-04-08 14:38 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                "     FROM likes " +
В этом классе есть ряд запросов с вложенными подзапросами.
Вообще не допускается, но,  поскольку рекомендации например  работают корректно, может быть можно оставить.
Стоит посоветоваться с наставником.
Возможно стоит упростить, разбив на несколько запросов, чтобы добиться удобной поддержки кода

2023-04-09 00:52 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  import lombok.extern.slf4j.Slf4j;
Потому что у тебя ошибка в запросе : пропущена буква "s" в слове "directors", поэтому и не парсится поле.

2023-04-09 00:54 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getSortedFilmByQuery(@RequestParam(value = "query", required = false) String query,
Аналогично, некорректный запрос

2023-04-10 02:47 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>  import lombok.extern.slf4j.Slf4j;
Исправила

2023-04-10 17:17 UTC, alexexus approved these changes

2023-04-10 17:27 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        return directorStorage.getDirectorById(id);
Переделали

2023-04-10 17:27 UTC, Natal1a-Chuklina commented on pom.xml
>  		<dependency>
Добавили

2023-04-10 17:27 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        return directorStorage.getDirectorById(id);
Переделали

2023-04-10 17:28 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                "     FROM likes " +
Убрали вложенные подзапросы

2023-04-11 14:58 UTC, z8q approved these changes

2023-04-14 01:35 UTC, merged