Реализованы добавление пользователей в друзья и возможность поставить лайк фильму
Natal1a-Chuklina/java-filmorate pull request #2
Opened 2023-02-20 16:17 UTC by Natal1a-Chuklina

2023-02-21 16:04 UTC, z8q requested changes
Привет!
Комментарии оставил)

2023-02-21 16:04 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  @Slf4j
Аннотацию оставили, а логи убрали.
Но на самом деле хорошо использовать логирование на уровне контроллеров.
Мы сообщаем о том, что запрос пришел и начинаем выполнение, пример:
`log.info("Creating film {}", film);`
В случае, если будут падения, мы добавим в лог сообщение об ошибке. В случае успешного выполнения добавим в лог информацию об успехе.

2023-02-21 16:04 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
Будет ли работать без `@Autowired`? На втором контроллере тоже нужно посмотреть

2023-02-21 16:04 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(FilmStorage filmStorage, UserStorage userStorage) {
Тоже не хватает `@Autowired`

2023-02-21 16:04 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final List<Integer> likes;
Можно было бы тут и в User использовать Set в качестве коллекции, чтобы избежать повторов

2023-02-21 16:04 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userStorage.getUser(userId).getFriends().stream().filter(friendId -> userStorage.getUser(otherId)
Если будешь использовать Set для хранения списка друзей, то можно рассмотреть использование метода у HashSet – retainAll() для выборки общих друзей

2023-02-21 16:04 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public UserService(UserStorage userStorage) {
`@Autowired`

2023-02-21 17:00 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
Аннотация не нужна, когда в классе только один конструктор. Все работает, иначе тесты бы не прошли.

2023-02-21 18:16 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  @Slf4j
Логи добавила

2023-02-21 18:17 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final List<Integer> likes;
Коллекции поменяла

2023-02-21 18:18 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userStorage.getUser(userId).getFriends().stream().filter(friendId -> userStorage.getUser(otherId)
Оставила стримы

2023-02-22 10:32 UTC, z8q approved these changes

2023-03-05 16:47 UTC, merged