Добавлена база H2 в проект
Natal1a-Chuklina/java-filmorate pull request #3
Opened 2023-03-18 13:16 UTC by Natal1a-Chuklina

2023-03-19 12:50 UTC, z8q requested changes

2023-03-19 12:50 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/dto/user/UserResponse.java
> +public class UserResponse {
Использовать dto это хорошо.
Но реализовано не совсем правильно. Можно посоветоваться с наставником, но рекомендую все таки использовать либо одну сущность, либо одну dto.
Если какие-то поля не используются в сценариях. Например при create нам принимать id не нужно,
Мы можем просто не обрабатывать это поле. Задавать id просто перед сохранением сущности.

2023-03-19 12:50 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public int add(CreateFilmRequest film) {
Отправляю POST запрос такого вида:
{
	"name": "Die Hard",
	"description": "Action movie with Br-s Wil-s",
	"releaseDate": "1988-07-22",
	"duration": 1234567,
	"rating": 100,
	"mpa": {
		"id": 5,
		"name":"NC-17",
		"description": "17+"
	},
	"genres": [ `в жанрах не указал id, чтобы появлялась ошибка`
		{
			"name": "action"
		},
		{
			"name": "drama"
		},
		{
			"name": "comedy"
		}
	]
}

Приходит такая ошибка:
{
	"errorMessage": "PreparedStatementCallback; SQL [INSERT INTO film_genre (film_id, genre_id) VALUES (?, ?);]; Referential integrity constraint violation: \"FK_GENRE_ID: PUBLIC.FILM_GENRE FOREIGN KEY(GENRE_ID) REFERENCES PUBLIC.GENRES(ID) (0)\"; SQL statement:\nINSERT INTO film_genre (film_id, genre_id) VALUES (?, ?) [23506-214]; nested exception is org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Referential integrity constraint violation: \"FK_GENRE_ID: PUBLIC.FILM_GENRE FOREIGN KEY(GENRE_ID) REFERENCES PUBLIC.GENRES(ID) (0)\"; SQL statement:\nINSERT INTO film_genre (film_id, genre_id) VALUES (?, ?) [23506-214]"
}

Не очень хорошо показывать пользователю внутренние sql запросы. Ошибка должна быть более понятная.
Плюс фильм в итоге сохраняется не смотря на ошибку.
Было бы правильно не сохранять объект, если возникает ошибка.
Также программа допускает добавление фильмов с одинаковыми полями, можно ограничить.

Запросы можно отправлять через postman или insomnia.
Смотреть результаты сохранения либо в базе через идею, либо через консоль http://localhost:8080/h2-console.
Или можно просто get запросами смотреть, сохранился объект после ошибки или нет

2023-03-19 12:50 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Collection<UserResponse> getAll() {
Когда запрашиваем пользователей, можно было бы показывать поле с друзьями тоже

2023-03-19 12:50 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                "SELECT f.id, " +
Sql запросы по всему коду красиво сделаны

2023-03-20 05:27 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public int add(CreateFilmRequest film) {
Тут я увидела сразу несколько проблем и их исправила:
1) При таком запросе у меня должна была возвращаться ошибка валидации, но так как я допустила ошибку этого не происходило, ошибку исправила, все работает.
2) В случае неизвестных ошибок пользователю выводилось сообщение ошибки (e.getMessage()). В данной ситуации это сообщение содержало SQL запрос, чтобы в дальнейшем не вывести случайно лишнюю информацию я заменила вывод сообщения ошибки на вывод заранее заданного мной сообщения.

Проблему добавления фильмов с одинаковыми полями решила. Теперь если у фильмов совпадают имя, описание, дата релиза и длительность, то фильм не добавляется.

И постманом, и консолью я активно пользуюсь. В консоли было удобно составлять запросы для проекта, так как сразу было видно, получаю ли я всю нужную информацию или нет, так же были видны дублирования названий колонок, которые в дальнейшем моли привести к ошибке.

2023-03-20 14:13 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Collection<UserResponse> getAll() {
Добавила.

2023-03-20 14:13 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/dto/user/UserResponse.java
> +public class UserResponse {
Переделала.

2023-03-20 18:21 UTC, z8q approved these changes

2023-03-23 09:36 UTC, merged