ветка add-remove-endpoint
Natal1a-Chuklina/java-filmorate pull request #4
Opened 2023-03-28 11:36 UTC by AleksandrGimanov

2023-03-28 11:58 UTC, kriulkin requested changes
все классно! небольшая помарка по чекстайлу :)

2023-03-28 11:58 UTC, kriulkin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public void deleteUser(int userId){
по чекстайлу не хватает перевода строки перед методом, и не хватает проблема перед {

2023-03-28 14:46 UTC, Natal1a-Chuklina commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:./db/filmorate
Это изменение приведет к тому, что после перезапуска приложения все данные из БД пропадут. Ты уверен, что это стоит делать?

2023-03-28 14:46 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        final String genresSqlQuery = "DELETE FROM film_genre WHERE film_id = ?";
Отдельный запрос для удаления жанров у фильма можно убрать, так как из-за режима ON DELETE CASCADE для id фильма в таблице film_genre жанры фильма и так будут удалены при удалении фильма.

2023-03-28 14:46 UTC, Natal1a-Chuklina commented on src/main/resources/schema.sql
> +	on update cascade ON DELETE CASCADE;
Лучше заменить ON DELETE CASCADE на ON DELETE RESTRIC или ON DELETE SET DEFAULT, так как некорректно удалять целый фильм, если удален рейтинг, на который ссылается этот фильм.

2023-03-28 14:46 UTC, Natal1a-Chuklina commented on src/main/resources/schema.sql
> +	on update cascade ON DELETE CASCADE;
Ситуация аналогична ситуации выше. Если нечаянно удалится какой-то из статусов дружбы, то все записи дружбы с таким статусом пропадут. Лучше запретить удаления статусов, т.е. заменить ON DELETE CASCADE на ON DELETE RESTRIC.

2023-03-28 14:46 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        filmService.deleteFilm(id);
Здесь можно добавить логирование, что получен запрос на удаление фильма.

2023-03-28 14:46 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public void deleteUser(@PathVariable int userId) {
Аналогично, можно добавить логирование.

2023-03-28 14:46 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            log.warn("Выполнена попытка получить фильм по несущестующему id = {}", filmId);
В данном случае выполняется не попытка получить фильм по несуществующему id, а удалить, несуществующий фильм. Лучше изменить сообщение для логирования, чтобы логи были более информативны.

2023-03-28 14:46 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            log.warn("Выполнена попытка получить пользователя по несущестующему id = {}", userId);
Аналогично ситуации с фильмом лучше изменить сообщение для вывода в логи.

2023-03-29 11:47 UTC, Natal1a-Chuklina approved these changes

2023-03-29 11:51 UTC, Natal1a-Chuklina approved these changes

2023-03-29 11:51 UTC, kriulkin approved these changes

2023-03-29 11:56 UTC, merged