Add director
Natal1a-Chuklina/java-filmorate pull request #6
Opened 2023-03-29 11:55 UTC by alexexus

2023-03-30 02:10 UTC, Natal1a-Chuklina requested changes

2023-03-30 02:10 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +public class DirectorController {
Стоит добавить логирование получения всех запросов, примеры можно посмотреть в контроллерах пользователей/фильмов/жанров/рейтингов.

2023-03-30 02:10 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    public Director addDirector(@Valid @RequestBody Director director) {
В модели директора нет валидации никаких полей, поэтому аннотация @Valid избыточна.

2023-03-30 02:10 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    private void validate(Director director) {
Если отправить POST запрос с телом: {} по эндпоинту /directors в этом методе будет вылетать NPE. Метод isEmpty() избыточен, так как метод isBlank() уже проверяет, что строка не пустая. Стоит рассмотреть вариант замены этого метода на аннотацию в модели директора.

2023-03-30 02:10 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getSortedFilmsByDirId(@PathVariable long directorId,
Стоит добавить логи.

2023-03-30 02:10 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +public class ValidationException extends RuntimeException {
Нет обработки этой ошибки в ErrorHandler, из-за чего пользователю выводится сообщение, что произошла неизвестная ошибка, хотя ошибка известна.

2023-03-30 02:10 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +            throw new NotFoundException("Director not found");
Сообщение о том, что режиссер не найден стоит вынести в класс с константами(Constants). Сообщение можно сделать более информативным для пользователя, добавив в него вывод id, по которому пытались получить режиссера. Разный язык сообщений выглядит несколько странно (все прошлые сообщения пользователю были на русском языке).

2023-03-30 02:10 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +public class DirectorService {
Во всех методах, в которых выбрасывается исключение, стоит добавить логирование. Проверку наличия режиссера в базе можно вынести в отдельный метод.

2023-03-30 02:10 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +    public Director updateDirector(Director director) {
Нет валидации имени режиссера при его обновлении, что позволяет сделать режиссеру пустое или null имя.

2023-03-30 02:10 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!directorStorage.directorExists(directorId)) {
Стоит добавить логирование. Про сообщение об ошибке уже писала.

2023-03-30 02:10 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorStorage.java
> +    boolean directorExists(long id);
Обычно названия методов, возвращающих boolean значение начинаются с is или has.

2023-03-30 02:10 UTC, Natal1a-Chuklina commented on src/main/resources/schema.sql
> +    director_name text
Можно добавить ограничение на имя not null.

2023-03-30 02:10 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDbStorage.java
> +public class DirectorDbStorage implements DirectorStorage {
Стоит добавить логирование.

2023-03-30 02:10 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            String sqlQuery = "DELETE FROM FILM_DIRECTOR WHERE FILM_ID = ?";
Строки 328, 329 дублируют строки 334, 335 и будут выполнены всегда, их можно вынести перед if.

2023-03-30 02:10 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        directorListWithoutDuplicate.sort((g1, g2) -> (int) (g1.getId() - g2.getId()));
Зачем тут нужна сортировка?

2023-03-30 02:10 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        film.setDirectors(getDirectorsByFilmId(film.getId()));
Можно не заполнять директоров в фильме, так как в сервисе после выполнения обновления фильма будет вызван метод получения фильма по id.

2023-03-30 02:10 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        } else {
Для любого значения sort кроме likes будет выводиться один и тот же результат, т.е. даже если пользователь укажет в sortBy не year, а duration, ему выведется список фильмов отсортированный по годам. Лучше для любых неизвестных значений сортировки выбросить ошибку и вывести сообщение, что приложение пока такую сортировку не делает (это лучше обрабатывать в сервисе).

2023-03-30 02:10 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public List<Film> getSortedFilmsByDirId(long directorId, String sort) {
Возможно, стоит этот метод разбить на два метода сортировки по лайкам и по годам?

2023-03-30 02:10 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    @Override
В новых методах стоит добавить логирование.

2023-03-30 02:10 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        addDirectors(filmId, film.getDirectors());
Если при создании фильма передать директора без id или с несуществующим id, выведется сообщение пользователю, что произошла неизвестная ошибка, но при этом фильм будет добавлен в бд. Аналогичная ситуация происходит при обновлении фильма.

2023-03-30 13:01 UTC, alexexus commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        directorListWithoutDuplicate.sort((g1, g2) -> (int) (g1.getId() - g2.getId()));
Потому что когда из сета создается лист, там почему-то идут айдишники в обратном порядке типа 3, 2, 1, а надо чтобы было 1, 2, 3

2023-03-30 13:39 UTC, Natal1a-Chuklina requested changes

2023-03-30 13:39 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +        log.info("Попытка добавить режиссера с id = {}", director.getId());
При создании режиссера поле id может быть пустым, либо его значение не учитывается, в логи будет выводиться противоречивая информация. Логи: 
   Попытка добавить режиссера с id = 10
   Добавлен режиссер с id = 4
   Попытка добавить режиссера с id = 0
   Добавлен режиссер с id = 5
Обычно логи нужны, чтобы отловить баг в программе. В данном случае бага нет, но логи могут натолкнуть на мысль, что баг есть, так как почему-то выполняется попытка добавить режиссера с id = 10, а в итоге добавляется режиссер с id = 4.

2023-03-30 13:39 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new NotFoundException("Существует сортировка только по year или likes");
Тут хорошо было бы добавить лог с сообщением, какую сортировку пытался выполнить пользователь.

2023-03-30 13:39 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleValidationException(ru.yandex.practicum.filmorate.exception.ValidationException e) {
После того, как ты свою валидацию заменил на валидацию через аннотацию, этот exception нигде в коде не используется. Его можно удалить. Так же, ты мог не создавать свою кастомную ошибку валидации, а использовать уже существующий ValidationException.

2023-03-30 13:39 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
>      private Set<Director> getDirectorsByFilmId(long filmId) {
Метод не используется.

2023-03-30 13:46 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        directorListWithoutDuplicate.sort((g1, g2) -> (int) (g1.getId() - g2.getId()));
Для реляционной бд порядок строк не должен иметь значения, у тебя же этот принцип нарушается.

2023-03-31 06:00 UTC, alexexus commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new NotFoundException("Существует сортировка только по year или likes");
Есть в контроллере
![image](https://user-images.githubusercontent.com/93264672/229035974-6cab6a62-86c0-4d53-95f0-219617f01843.png)

2023-03-31 06:06 UTC, alexexus commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        directorListWithoutDuplicate.sort((g1, g2) -> (int) (g1.getId() - g2.getId()));
Причем тут бд, мне нужно чтобы в листе было нужная сортровка

2023-03-31 07:46 UTC, Natal1a-Chuklina requested changes

2023-03-31 07:46 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +public class ValidationException extends RuntimeException {
Класс не используется.

2023-03-31 07:59 UTC, Natal1a-Chuklina approved these changes

2023-03-31 08:12 UTC, AleksandrGimanov approved these changes
Все хорошо

2023-03-31 08:12 UTC, merged