feat: Добавил функционал "Отзывы"
Natal1a-Chuklina/java-filmorate pull request #7
Opened 2023-03-30 12:59 UTC by AndreyMeltsov

2023-03-30 13:22 UTC, alexexus requested changes

2023-03-30 13:22 UTC, alexexus commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.info("Review is added: {}", review);
Наташа скажет переделать на русский язык

2023-03-30 13:22 UTC, alexexus commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +            throw new NotFoundException("Review with such id wasn't found in DB");
Эту проверку наверное надо сделать в сервисе

2023-03-30 13:22 UTC, alexexus commented on src/main/resources/schema.sql
> +);
![image](https://user-images.githubusercontent.com/93264672/228848998-b53f6f4f-2455-4d09-a8f2-df56244d46a4.png)
Не знаю зачем в конце всех классов и файлов нужно оставлять пустую строчку, мне об этом говорил мой ревьюер, ну и гитхаб тоже это замечает, так что, наверное, надо добавить

2023-03-30 13:23 UTC, alexexus commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.info("Review is added: {}", review);
Везде

2023-03-30 13:36 UTC, AleksandrGimanov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (reviewStorage.isReviewExists(id)) {
слишком часто повторяется код        if (reviewStorage.isReviewExists(id)) {
            log.warn("Выполнена попытка получить отзыв по несущестующему id = {}", id);
            throw new NotFoundException(String.format(Constants.REVIEW_NOT_FOUND_MESSAGE, id));
  можно вынести в отдельный метод с последующим вызовом. ну и соответственно с другими проверками тоже можно обьеденить

2023-04-01 07:38 UTC, alexexus approved these changes

2023-04-01 15:02 UTC, Natal1a-Chuklina requested changes

2023-04-01 15:02 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +public class ReviewController {
Не хватает логирования, пример можно посмотреть в других контроллерах.

2023-04-01 15:02 UTC, Natal1a-Chuklina commented on src/main/resources/schema.sql
> +create TABLE IF NOT EXISTS reviews_likes (
Для того, чтобы бд находилась во второй нормальной форме (https://info-comp.ru/second-normal-form) необходимо, чтобы у всех ее таблиц был первичный ключ. Таблицы лайков и дизлайков отзыва не удовлетворяют этому условию.

2023-04-01 15:02 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +            @RequestParam(value = "count", defaultValue = "10", required = false) @Positive Integer count) {
Указывать required = false необязательно, если установлено значение по умолчанию (https://www.baeldung.com/spring-request-param#a-default-value-for-the-request-parameter).

2023-04-01 15:02 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +            @RequestParam(value = "count", defaultValue = "10", required = false) @Positive Integer count) {
Чтобы аннотация @ Positive работала, нужно поставить аннотацию @Validated перед классом (https://www.baeldung.com/spring-validate-requestparam-pathvariable#configuration).

2023-04-01 15:02 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    @NonNull
В NonNull тут нет необходимости, так как в NotBlank уже есть проверка на null (https://www.baeldung.com/java-bean-validation-not-null-empty-blank#the-@notblank-constraint).

2023-04-01 15:02 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    @NonNull
Лучше аннотации NonNull от lombok заменить на NotNull (import javax.validation.constraints.NotNull;). Так как в случае аннотации NonNull POST запрос по эндпоинту /reviews с телом:
{
  "content": "This film is soo bad.",
  "isPositive": false,
  "filmId": 1
} 
выведет пользователю сообщение: "Произошла неизвестная ошибка, попробуйте проверить корректность всех данных запроса", при этом 175 строчка в FilmService вызовет NPE. В случае NotNull проверка поля на null будет выполнена при валидации тела запроса и в случае такого же запроса выдаст обрабатываемую ошибку валидации и более корректное сообщение пользователю.

2023-04-01 15:02 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +            @RequestParam(value = "count", defaultValue = "10", required = false) @Positive Integer count) {
Лучше значение по умолчанию вынести в приватное финальное статическое поле класса (константу), чтобы, во-первых, избавиться от магического числа в коде, а, во-вторых, облегчить себе жизнь в возможном будущем. Т.к. если попросят изменить значение по умолчанию на другое, то в этом случае придется сначала искать среди всех методов класса нужный метод, а потом менять в нем значение, если же значение по умолчанию вынести в константу класса, то метод искать не придется, достаточно будет поменять значение константы.

2023-04-01 15:02 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +            return filmService.getAllReviews();
Мне кажется, что в случае отсутствия id фильма ожидается немного другое поведение программы: выводится либо указанное пользователем количество отсортированных отзывов, либо 10 отсортированных отзывов, если пользователь не указал число.

2023-04-01 15:02 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Review createReview(Review review) {
Новую логику работы приложения с отзывами лучше вынести в отдельный сервис (ReviewService).

2023-04-01 15:02 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (reviews != null) {
Как и в методе getAllReviews можно не делать проверку на null, так как в любом случае будет возвращен либо заполненный, либо пустой список.

2023-04-01 15:02 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewDbStorage.java
> +    public boolean isReviewExists(Integer id) {
Название метода противоречит возвращаемому значению: ожидается что метод isReviewExist (существует ли отзыв) будет возвращать true. если отзыв существует, false - если нет, а получается наоборот.

2023-04-01 15:02 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Review createReview(Review review) {
Сейчас один пользователь может создать бесконечное число отзывов на один и тот же фильм, стоит подумать хорошее ли это поведение программы. Кроме того, эти отзывы могут быть абсолютно идентичны, т.е. одно и то же содержание и положительность.

2023-04-01 15:02 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void addLikeToReview(Integer id, Integer userId) {
С лайками и дизлайками стоит еще поработать: один пользователь может лайкнуть/дизлайкнуть отзыв бесконечное число раз, так не должно быть. Пользователь, который не ставил лайк/дизлайк отзыву при удалении лайка/дизлайка какого-то отзыва может изменять его счетчик полезности, т.е. лайк/дизлайк не удаляется, так как его нет, а вот счетчик меняется.

2023-04-02 05:10 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +public class ReviewController {
Все логирование сделано в сервисе. Мне ревьюер на пред спринте сказал, что должно быть там.

2023-04-02 05:19 UTC, AndreyMeltsov commented on src/main/resources/schema.sql
> +create TABLE IF NOT EXISTS reviews_likes (
В статье которую ты привела, обрати внимание на последнюю таблицу, там где 2 столбца: "Идентификатор проекта", "Идентификатор участника". Там нет никакого РК для этих записей. У меня таблицы лайков и дизлайков аналогичны, там ид отзывов и ид юзеров, и доп ключа считаю там не требуется.

2023-04-02 05:53 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +            return filmService.getAllReviews();
Не соглашусь. Мы должны иметь возможность посмотреть все отзывы. К тому же именно это сказано в задании:
GET /reviews?filmId={filmId}&count={count}
Получение всех отзывов по идентификатору фильма, если фильм не указан то **все**. Если кол-во не указано то 10.

2023-04-02 09:47 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +public class ReviewController {
Меня ревьюер просил добавить логирование входящих запросов в контроллере:
"Но на самом деле хорошо использовать логирование на уровне контроллеров.
Мы сообщаем о том, что запрос пришел и начинаем выполнение, пример:
log.info("Creating film {}", film);
В случае, если будут падения, мы добавим в лог сообщение об ошибке. В случае успешного выполнения добавим в лог информацию об успехе.".

2023-04-02 09:59 UTC, AndreyMeltsov commented on src/main/resources/schema.sql
> +create TABLE IF NOT EXISTS reviews_likes (
Разобрался что ты имела ввиду, добавил в РК в таблицы

2023-04-02 13:01 UTC, Natal1a-Chuklina requested changes

2023-04-02 13:01 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +    boolean hasUserAlreadyLeftLikeForFilm(Integer reviewId, Integer userId);
В данном случае идет проверка ставил ли пользователь уже лайк отзыву, а не фильму (в следующем методе аналогично, только с дизлайком).

2023-04-02 13:01 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        boolean hasUserAlreadyLeftReviewForFilm = getReviewsByFilmId(filmId, getAllReviews().size())
Возможно быстрее будет работать через запрос к бд.

2023-04-02 13:01 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        if (reviewStorage.hasUserAlreadyLeftDislikeForFilm(id, userId)) {
Это ты классно придумал))

2023-04-03 05:37 UTC, Natal1a-Chuklina approved these changes

2023-04-03 05:37 UTC, merged