ТЗ12 - add-search
Natal1a-Chuklina/java-filmorate pull request #9
Opened 2023-03-31 12:27 UTC by alexexus

2023-04-01 08:37 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.info("Попытка получить топ 10 фильмов по лайкам");
"Попытка получить топ 10 фильмов по _популярности_"

2023-04-01 09:09 UTC, AndreyMeltsov requested changes

2023-04-01 09:09 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            sqlQuery = "SELECT f.id, " +
Мне кажется повторяющийся код в запросе можно вынести в отдельную константу

2023-04-01 09:09 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        if (by.equals("director,title")) {
Может else if?

2023-04-01 09:09 UTC, AndreyMeltsov commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        if (by.equals("director")) {
Может уйти от if-else и попробовать switch-case?

2023-04-02 10:26 UTC, AndreyMeltsov approved these changes

2023-04-02 14:32 UTC, Natal1a-Chuklina requested changes

2023-04-02 14:32 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                        "GROUP BY D.DIRECTOR_NAME ORDER BY D.DIRECTOR_NAME";
Нужно корректировать группировки: во-первых, лучше группировать по Id, т.к. у разных фильмов могут быть одинаковые названия или у разных режиссеров могут быть одинаковые имена. А, во-вторых, если добавить больше одного фильма одному режиссеру и сделать поиск по режиссеру, то будет вылетать ошибка (это не единственный случай, вызывающий ошибку). Попробуй заполнить бд данными и в консоли потренироваться делать запросы с разной группировкой.

2023-04-02 14:32 UTC, Natal1a-Chuklina commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        switch (by) {
Если String by будет содержать строку отличную от рассмотренных случаев, то будет вылетать ошибка. Этот случай можно обработать в сервисе и вывести сообщение пользователю, что нет поиска по такому параметру.

2023-04-03 14:26 UTC, Natal1a-Chuklina approved these changes

2023-04-03 14:26 UTC, merged